<?php

// Language definitions used in all admin files
$lang_admin_groups = array(

// admin_groups
'Group settings heading'		=>	'當討論版面沒有特別設定權限時，會套用群組預設的權限',
'Group title label'				=>	'群組名稱',
'User title label'				=>	'會員頭銜',
'Group title head'				=>	'群組名稱與會員頭銜',
'Group title legend'			=>	'設定頭銜',
'Group perms head'				=>	'群組權限',
'Group flood head'				=>	'群組防灌水保護設定',
'User title help'				=>	'在這個群組裡設定的頭銜將會取代任何會員等級名稱。要使用預設頭銜或是等級名稱請保持本欄空白。',
'Remove group legend'			=>	'移除群組',
'Permissions'					=>	'權限許可',
'Moderation'					=>	'版面管理',
'Allow moderate label'			=>	'允許會員管理版面的權限。',
'Allow mod edit profiles label'	=>	'允許版面管理員可以編輯會員的個人資料。',
'Allow mod edit username label'	=>	'允許版面管理員可以更改會員名稱。',
'Allow mod change pass label'	=>	'允許版面管理員可以更換會員密碼。',
'Allow mod bans label'			=>	'允許版面管理員可以封鎖會員。',
'Allow read board label'		=>	'允許會員可以瀏覽版面。',
'Allow read board help'			=>	'這項設定會套用到整個論壇，如果這裡設定為"否"，亦無法藉由編輯討論版面來更改瀏覽版面的權限。且在這個群組裡的會員將只能做登入/登出和註冊。',
'Allow view users label'		=>	'允許會員可以檢視會員列表與會員個人資料。',
'Allow post replies label'		=>	'允許會員可以在主題中回覆文章。',
'Allow post topics label'		=>	'允許會員可以發表新的主題。',
'Allow edit posts label'		=>	'允許會員可以編輯他們自己的文章。',
'Allow delete posts label'		=>	'允許會員可以刪除他們自己的文章。',
'Allow delete topics label'		=>	'允許會員可以刪除他們自己發表的主題 (包含裡頭任何的文章回覆)',
'Allow set user title label'	=>	'允許會員可以設定他們自己的會員頭銜。',
'Allow use search label'		=>	'允許會員可以使用搜尋功能。',
'Allow search users label'		=>	'允許會員可以利用會員列表搜尋會員。',
'Allow send email label'		=>	'允許會員可以寄送電子郵件給其他會員。',
'Restrictions'					=>	'限制',
'Mod permissions'				=>	'版面管理權限',
'User permissions'				=>	'會員權限',
'Flood interval label'			=>	'文章發表時間間隔',
'Flood interval help'			=>	'在這個群組裡的會員於發表文章後需等待幾秒，才能發表下一篇文章。設定本欄為 0 來取消這個限制。',
'Search interval label'			=>	'搜尋資料時間間隔',
'Search interval help'			=>	'在這個群組裡的會員於搜尋資料後需等待幾秒，才能進行下一次搜尋。設定本欄為 0 來取消這個限制。',
'Email flood interval label'	=>	'郵件寄送時間間隔',
'Email flood interval help'		=>	'在這個群組裡的會員於電子郵件寄送後需等待幾秒，才能進行下一次寄送。設定本欄為 0 來取消這個限制。',
'Allow moderate help'			=>	'為了要使這個群組裡的某個會員擁有版面管理的能力，他/她必須被指定管理一個或更多個討論版面。這可以透過會員管理，於其個人資料中的管理員設定項來做設定。',
'Remove group'					=>	'移除這個群組',
'Edit group'					=>	'編輯這個群組',
'default'						=>	'(預設群組)',
'Cannot remove group'			=>	'這個群組不能被移除。',
'Cannot remove default'			=>	'要移除這個群組的話，您必須先設定另一個群組當作預設群組。',
'Remove group head'				=>	'要移除的 "%s" 群組裡頭包含 %s 位會員',
'Remove group help'				=>	'(轉移當前的會員到這個群組)',
'Move users to'					=>	'移動會員到',
'Cannot remove default group'	=>	'預設群組不能被移除。要移除這個群組的話，您必須先設定另一個群組當作預設群組。',
'Add group heading'				=>	'新增群組 (新建立的群組將會繼承您所選擇的會員群組的權限設定)',
'Add group legend'				=>	'新增群組',
'Edit group heading'			=>	'編輯目前存在的群組',
'Base new group label'			=>	'以哪個群組為範本',
'Add group'						=>	'新增群組',
'Default group heading'			=>	'預設群組將會成為新註冊會員一開始加入的群組。(基於安全性理由，版面管理員或是論壇管理員群組不包含在下列選項內)',
'Default group legend'			=>	'設定給新會員使用的預設群組',
'Default group label'			=>	'預設群組',
'Set default'					=>	'設定預設',
'Existing groups heading'		=>	'目前存在的群組',
'Existing groups intro'			=>	'這裡預先定義好的訪客(Guest)、論壇管理員(Administrators)等群組不能移除，但它們仍然可以讓您做編輯。話雖如此，在某些群組裡，某些設定功能是不提供的。(舉例來說，訪客是不具備"編輯文章"的權限的)。論壇管理員則是擁有完整的權限。',
'Group removed'					=>	'群組已移除。',
'Default group set'				=>	'預設群組已設定。',
'Group added'					=>	'群組已新增。',
'Group edited'					=>	'群組已編輯。',
'Update group'					=>	'更新群組',
'Must enter group message'		=>	'您必須輸入一個群組名稱。',
'Already a group message'		=>	'已經有一個同樣名稱為 <strong>"%s"</strong>的群組。',
'Moderator default group'		=>	'由於這個是給新會員一開始加入的預設群組，它不能被指定擁有版面管理的權限。',

);
