<?php

// Language definitions used in all admin files
$lang_admin_bans = array(

'Ban advanced'					=>	'封鎖進階設定',
'Ban advanced heading'			=>	'封鎖會員名稱與 IP 位址和電子郵件，或只封鎖 IP 位址 / 電子郵件，或兩者兼用',
'Ban criteria legend'			=>	'封鎖條件',
'Ban settings legend'			=>	'封鎖設定',
'Ban IP warning'				=>	'<strong>警告！</strong> 當您封鎖一組 IP 區段的時候必須要非常小心，因為這樣做可能會造成多位符合該 IP 區段條件的使用者同時被封鎖。',
'Current ban head'				=>	'由 %s 建立封鎖',
'Username'						=>	'會員名稱:',
'Username to ban label'			=>	'要封鎖的會員名稱',
'Ban creator'					=>	'封鎖建立者',
'IP-addresses to ban label'		=>	'要封鎖的 IP 位址',
'IP-addresses help'				=>	'想要封鎖的 IP 或 IP 區段 (例如︰150.11.110.1 或 150.11.110)。各位址間請以空白鍵做為區隔。如果指定的會員名稱之前曾經於本欄輸入過 IP，那麼這裡再填的 IP 將做為該會員名稱最後已知的 IP 並存入封鎖清單中。',
'IP-addresses help stats'		=>	'點選下列連結來檢視這名會員的 IP 狀態: ',
'IP-addresses help link'		=>	'會員 IP 狀態',
'E-mail/domain to ban label'	=>	'要封鎖的電子郵件/網域名稱',
'E-mail/domain help'			=>	'想要封鎖的電子郵件或者是郵件網域 (例如︰someone@example.com 或 example.com)。請看 功能設定 - 會員註冊 裡的 "註冊電子郵件" 設定項來獲得更多資訊。',
'Ban message label'				=>	'封鎖訊息',
'Ban message help'				=>	'這則訊息將會在該名被封鎖的會員瀏覽論壇的時候顯示給他/她看',
'Expire date label'				=>	'封鎖期滿日期',
'Expire date help'				=>	'這項封鎖將會在指定期滿日期到達時自動解除封鎖設定 (日期格式︰YYYY-MM-DD)。保持本欄空白表示要採取手動移除封鎖。',
'Expires'						=>	'封鎖期滿日期:',
'Message'						=>	'封鎖訊息:',
'New ban heading'				=>	'封鎖指定的會員名稱',
'New ban legend'				=>	'最新封鎖',
'Advanced ban info'				=>	'在下一設定頁將可讓您設定 IP 和電子郵件資訊。如果您只是想要封鎖某個特定的 IP / IP 區段或者是電子郵件，請保持本欄空白，直接點擊新增進入下一設定頁。',
'Existing bans heading'			=>	'編輯或移除目前存在的封鎖設定',
'Add ban'						=>	'新增封鎖',
'Save ban'						=>	'儲存封鎖',
'E-mail'						=>	'電子郵件地址:',
'IP-ranges'						=>	'IP 位址/IP 區段',
'Reason'						=>	'理由',
'No bans'						=>	'目前清單中沒有任何封鎖項目。',
'Edit ban'						=>	'編輯封鎖',
'Remove ban'					=>	'移除封鎖',
'Edit or remove'				=>	'%s 或 %s',
'Ban removed'					=>	'封鎖已移除。',
'Ban added'						=>	'封鎖已新增。',
'Ban edited'					=>	'封鎖已編輯。',
'No user id message'			=>	'沒有會員使用此 ID。',
'No user username message'		=>	'找不到使用這個會員名稱註冊的會員。如果您要新增封鎖的條件並不是某一特定的會員名稱，請保持該欄空白。',
'User is admin message'			=>	'該會員是論壇管理員且不能被封鎖。如果您要封鎖一位論壇管理員，必須先將他/她移動到其他群組。',
'Must enter message'			=>	'您必須至少輸入會員名稱、IP 位址，或者是電子郵件地址等其中一個項目。',
'Invalid IP message'			=>	'您輸入的 IP 位址/IP 區段不正確。',
'Can\'t ban guest user'			=>	'訪客不能被封鎖。',
'Invalid e-mail message'		=>	'您輸入的電子郵件地址 (例如: user@example.com) 或者是郵件網域名稱 (例如: example.com) 不正確。',
'Invalid expire message'		=>	'您輸入一個不正確的期滿日期。日期格式應該為 YYYY-MM-DD 且日期必須是未來的某一天。',


);
