<?php

// Language definitions used in all admin files
$lang_admin_users = array(

// admin_users
'Search head'					=>	'搜尋會員',
'User search head'				=>	'您可以輸入一個或更多的條件來搜尋會員。在下列表單欄位裡可以使用萬用字元星號 <strong>*</strong> 來做模糊比對。',
'Searches personal legend'		=>	'個人資料',
'Username label'				=>	'會員名稱',
'Title label'					=>	'頭銜',
'Real name label'				=>	'真實姓名',
'Location label'				=>	'居住地',
'Signature label'				=>	'個人簽名',
'Admin note label'				=>	'管理員記錄',
'Searches contact legend'		=>	'聯絡資料',
'E-mail address label'			=>	'電子郵件地址',
'Website label'					=>	'個人網站',
'Searches activity legend'		=>	'會員活動',
'More posts label'				=>	'文章數大於幾篇',
'Less posts label'				=>	'文章數小於幾篇',
'Number of posts help'			=>	'(發表文章數)',
'Last post after label'			=>	'最後發文時間之後',
'Last post before label'		=>	'最後發文時間之前',
'Registered after label'		=>	'註冊時間之後',
'Registered before label'		=>	'註冊時間之前',
'Date format help'				=>	'[ yyyy-mm-dd hh:mm:ss ]',
'Jabber label'					=>	'Jabber',
'ICQ label'						=>	'ICQ',
'MSN Messenger label'			=>	'MSN Messenger',
'AOL IM label'					=>	'AOL IM',
'Yahoo Messenger label'			=>	'Yahoo! Messenger',
'User results head'				=>	'排序會員搜尋結果',
'User results legend'			=>	'搜尋結果',
'Order by label'				=>	'排序依照',
'Sort order label'				=>	'排序方式',
'User group label'				=>	'會員群組',
'IP search head'				=>	'在資料庫裡的文章中搜尋指定的 IP 位址。',
'IP search legend'				=>	'輸入 IP 位址來搜尋',
'IP address label'				=>	'IP 位址',
'User information'				=>	'會員資訊',
'IP address'					=>	'IP 位址',
'Username'						=>	'會員名稱',
'E-mail'						=>	'電子郵件地址',
'Admin note'					=>	'管理員記錄',

'Invalid IP address'			=>	'您輸入的 IP 位址格式不正確。',
'Users matching criteria'		=>	'符合搜尋條件的會員',
'User IP stats'					=>	'會員的 IP 狀態',
'IP matching criteria'			=>	'符合 IP 位址的搜尋結果',
'Users found'					=>	'搜尋到的會員 [ %s ]',
'IP addresses found'			=>	'搜尋到的 IP 位址 [ %s ]',
'Moderate users'				=>	'管理會員',
'Submit search'					=>	'提交搜尋',
'Not verified'					=>	'尚未驗證',
'Registered'					=>	'已註冊',
'Last post'						=>	'最後發文',
'Ascending'						=>	'遞增',
'Descending'					=>	'遞減',
'All groups'					=>	'所有群組',
'Unverified users'				=>	'未驗證的會員',
'Non numeric value message'		=>	'您在一個只能輸入數字的欄位輸入非數字的值。',
'Invalid date/time message'		=>	'您輸入的日期/時間格式不正確。',
'No search terms message'		=>	'您沒有輸入任何搜尋條件。',
'Delete users'					=>	'刪除會員',
'Delete warning'				=>	'<strong>警告！</strong> 刪除會員和其文章後便無法再復原。如果您選擇不要刪除該會員所貼過的文章，則那些文章在以後只能以手動的方式刪除。',
'Delete posts legend'			=>	'您可以選擇刪除這些會員所發表過的文章',
'Confirm delete'				=>	'確認刪除',
'Delete posts'					=>	'刪除文章',
'Delete posts label'			=>	'允許刪除這些會員所發表過的主題與文章。',
'Users deleted'					=>	'會員已刪除。',
'Ban'							=>	'封鎖',
'Ban users'						=>	'封鎖會員',
'Change group'					=>	'更改群組',
'Delete admin message'			=>	'論壇管理員無法被刪除。要刪除一位論壇管理員，您必須先將他/她移動到不同的會員群組。',
'Ban admin message'				=>	'所選擇的會員中包含論壇管理員，論壇管理員不能被封鎖。如果您要封鎖一位論壇管理員，必須先將他/她移動到其他群組。',
'Users banned'					=>	'會員已封鎖。',
'Mass ban info'					=>	'您可以設定一則顯示給封鎖會員看的訊息，以及設定封鎖期滿日期。',
'Ban settings legend'           =>  '封鎖會員', 
'Change group head'				=>	'移動選擇的會員到新的群組',
'User groups updated'			=>	'會員群組已更新。',
'Move users legend'				=>	'移動會員',
'No users selected'				=>	'尚未選擇會員',
'Move users to label'			=>	'移動會員到群組',

// admin_users tables
'Username column'				=>	'會員名稱 - 電子郵件 - 管理員記錄',
'Title column'					=>	'頭銜 - 狀態',
'Posts'							=>	'文章數',
'Actions'						=>	'可執行動作',
'View IP stats'					=>	'檢視 IP 狀態',
'Show posts'					=>	'顯示文章',
'Last used'						=>	'最後使用時間',
'Times found'					=>	'使用次數',
'Find more users'				=>	'尋找更多使用這組 IP 位址的會員',
'No posts by user'				=>	'該會員在論壇中沒有任何文章。',
'Guest'							=>	'訪客',
'Cannot find IP'				=>	'提供的 IP 位址在資料庫中查詢不到。',
'Not verified'					=>	'尚未驗證',
'No match'						=>	'沒有符合的資料',
'User search results'			=>	'會員搜尋結果'

);
