<?php

// Language definitions used in admin-categories
$lang_admin_forums = array(

'Edit forum head'				=>	'編輯版面: %s',
'Edit or delete'				=>	'%s 或 %s',
'Edit'							=>	'編輯',
'Delete'						=>	'刪除',
'Forum name'					=>	'版面名稱',
'Position label'				=>	'排列順序',
'Delete forum'					=>	'刪除討論版面',
'Delete forum warning'			=>	'<strong>警告！</strong> 刪除一個討論版面將會連同裡頭的文章一併刪除掉!',
'Edit forum'					=>	'編輯版面',
'Edit forum details legend'		=>	'版面細節',
'Category assignment'			=>	'指定論壇分區',
'Forums in category'			=>	'在論壇分區 %s 裡的討論版面',
'Edit forum perms legend'		=>	'版面群組權限 (非預設權限會在字尾加上 "(S)" 來做標記。)',
'Forum name label'				=>	'版面名稱',
'Position label'				=>	'排列順序',
'Add to category label'			=>	'新增至論壇分區',
'Forum description'				=>	'版面描述',
'Forum description help'		=>	'(您可以在版面描述中使用 HTML 語法)',
'Sort topics by'				=>	'主題排序依',
'Sort last post'				=>	'最後回覆',
'Sort topic start'				=>	'新開主題',
'Redirect URL'					=>	'重新導向連結',
'Only for empty forums'			=>	'僅在空的討論版面裡可以使用',
'Edit forums head'				=>	'編輯、刪除或更改討論版面的排列順序',
'Edit forum details head'		=>	'編輯版面細節',
'Edit forum perms head'			=>	'編輯版面權限',
'Post replies'					=>	'回覆文章',
'Post topics'					=>	'發表主題',
'User groups'					=>	'會員群組',
'Confirm delete forum'			=>	'您目前正打算刪除 "%s" 這個討論版面',
'Forum perms read info'			=>	'如果在會員群組裡已設定不具備瀏覽版面的權限時，下列"瀏覽版面"的選項將會變成無法勾選的狀態。',
'Forum perms redirect info'		=>	'目前此討論版面為外部連結。Only the "Read forum" permission is editable.',
'Forum perms restore info'		=>	'使用底下"回復預設權限"按鈕可以將權限設定回復成預設狀態。',
'Forum perms groups info'		=>	'這裡的權限設定預設與 %s 中所做的設定值相同。若有不同處，會在字尾加上 "(S)" 來做標記。',
'Forum perms admins info'		=>	'論壇管理員擁有完整的處理權限。',
'Not default'					=>	'(S)',
'Read forum'					=>	'瀏覽版面',
'Restore defaults'				=>	'回復預設權限',
'Add forum'						=>	'新增版面',
'Add forum head'				=>	'以指定的排列順序新增討論版面至所選擇的論壇分區',
'Add forum legend'				=>	'新增版面',
'Add to category'				=>	'新增至論壇分區',
'Update positions'				=>	'更新排列順序',
'Forum added'					=>	'討論版面已新增。',
'Forum deleted'					=>	'討論版面已刪除。',
'Forums updated'				=>	'討論版面已更新。',
'Forum updated'					=>	'討論版面已更新。',
'Permissions reverted'			=>	'權限回復至預設值。',
'Must enter forum message'		=>	'您必須輸入一個版面名稱。',

);