<?php

// Language definitions used in viewforum.php
$lang_forum = array(

'Forum subtitle'			=>	'%1$s 在此論壇，詳細信息: %2$s。',
'Search subtitle'			=>	'%1$s 找到，詳細信息: %2$s。',
'Topics'					=>	'主題',
'topics'					=>	'主題',
'Reply'						=>	'回覆',
'Replies'					=>	'回覆',
'Forum'						=>	'版面',
'reply'						=>	'回覆',
'replies'					=>	'回覆',
'View'						=>	'點閱',
'Views'						=>	'點閱',
'views'						=>	'點閱',
'view'						=>	'點閱',
'Last post'					=>	'最後發表',
'last post'					=>	'最後發表',
'Select topic'				=>	'選擇主題: %s。',
'No replies info'			=>	'無回覆資訊',
'No views info'				=>	'無點閱資訊',
'No lastpost info'			=>	'無最後發表資訊',
'by poster'					=>	'作者 %s',
'Item status'				=>	'%s :',
'Topic starter'				=>	'作者 %s',
'New posts'					=>	'新文章',
'Topic navigation'			=>	'( %s )',
'Location'					=>	'在版面: %s 內找到',
'Pages'						=>	'頁次',
'Post topic'				=>	'發表新主題',
'Login to post'				=>	'您必須 %1$s 或者 %2$s 才能發表新主題',
'No permission'				=>	'很抱歉！您沒有發表新主題的權限',
'Moved'						=>	'已移動:',
'Sticky'					=>	'[置頂]',
'Closed'					=>	'[關閉]',
'Empty forum'				=>	'空的討論版面',
'No topics'					=>	'目前沒有任何主題',
'First topic nag'			=>	'現在就在這個討論版面發表第一篇主題。',
'You posted indicator'		=>	'·',
'Permalink forum'			=>	'直接連結到這個討論版面。',
'Forum options'				=>	'版面選項',
'Moderate forum'			=>	'管理版面',
'Mark forum read'			=>	'標記版面成已讀',
'RSS forum feed'			=>	'訂閱本討論版 RSS Feed',
'New posts info'			=>	'前往上次最後瀏覽之後的最新文章。'

);
