<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'No search permission'		=>	'您沒有使用搜尋功能的權限。',
'Search heading'			=>	'輸入您的搜尋條件來搜尋論壇',
'Search flood'				=>	'必須等候至少 %s 秒才能再次進行搜尋。請您稍後再試。',
'Search legend'				=>	'搜尋條件',
'Results legend'			=>	'搜尋結果',
'Keywords info'				=>	'您可以輸入一個或一個以上的關鍵字當做搜尋條件。使用多個關鍵字，請用空格來做分隔。',
'Refine info'				=>	'您可以使用 <strong>AND</strong>，<strong>OR</strong> 和 <strong>NOT</strong> 搭配關鍵字來提升搜尋效果。',
'Wildcard info'				=>	'使用萬用字元 <strong>*</strong> 來做關鍵字或帳號名稱部份比對。',
'Forum default info'		=>	'在預設情況下，所有的版面都會被搜尋。您可以選擇一個或者多個版面來縮小搜尋範圍。',
'Forum require info'		=>	'您可以選擇搜尋一個或者多個版面。但您必須<strong>至少選擇一個版面</strong>來進行搜尋。',
'Keyword search'			=>	'關鍵字搜尋',
'Author search'				=>	'作者搜尋',
'Forum search'				=>	'搜尋版面',
'Forum search default'		=>	'如果沒有選擇任何版面，那麼所有的版面將會被搜尋。',
'Forum search require'		=>	'您必須至少選擇一個版面來搜尋。',
'Sort by'					=>	'排序結果依',
'Sort order'				=>	'排列順序',
'Sort by post time'			=>	'張貼時間',
'Sort by author'			=>	'作者',
'Sort by subject'			=>	'主題',
'Sort by forum'				=>	'版面',
'Ascending'					=>	'依序遞增',
'Descending'				=>	'依序遞減',
'Display results'			=>	'搜尋結果顯示方式',
'Show as topics'			=>	'列出主題',
'Show as posts'				=>	'列出個別文章',
'Submit search'				=>	'搜尋',
'User defined search'		=>	'會員定義的搜尋',
'Search in'					=>	'搜尋於',
'Message and subject'		=>	'文章內容和主題標題',
'Message only'				=>	'僅搜尋文章內容',
'Topic only'				=>	'僅搜尋主題標題',

// Results
'Search results'			=>	'搜尋結果',
'Topics with new'			=>	'包含新文章的主題',
'Recently active topics'	=>	'最近熱門的主題',
'Unanswered topics'			=>	'尚未回覆的主題',
'Subscriptions'				=>	'訂閱的主題',
'Topics found'				=>	'搜尋到的主題數',
'Posts found'				=>	'搜尋到的文章數',
'Topics by'					=>	'由 %s 發表的主題',
'Posts by'					=>	'由 %s 發表的文章',
'Topics by user'			=>	'該會員發表的主題',
'Posts by user'				=>	'該會員發表的文章',
'Perform new search'		=>	'執行新的搜尋',
'Search options'			=>	'搜尋選項',
'Posted in'					=>	'已發表在',
'No terms'					=>	'請輸入至少一個關鍵字或是一個作者名稱以供搜尋。',
'No hits'					=>	'沒有符合條件的文章。',
'No user posts'				=>	'本論壇沒有這位會員發表的文章。',
'No user topics'			=>	'本論壇沒有這位會員發表的主題。',
'No subscriptions'			=>	'您目前沒有訂閱任何主題。',
'No new posts'				=>	'自您上次來訪以來沒有新的文章。',
'No recent posts'			=>	'自過去24小時以來沒有新的文章。',
'No unanswered'				=>	'在這個論壇裡沒有無人回應的文章。',
'Go to post'				=>	'前往文章',
'Go to forum'				=>	'前往版面',
'Go to topic'				=>	'前往主題',
'Go to profile'				=>	'前往 %s 的個人資料區'

);
