<?php

// Russian language pack [PunBB.ru community ]
// Language definitions used in all admin files
$lang_admin_ext = array(

'Install extension'				=>	'Установка дополнения',
'Upgrade extension'				=>	'Обновить дополнение',
'Extensions available'			=>	'Дополнения для установки',
'Hotfixes available'			=>	'Исправления для установки',
'Installed extensions'			=>	'Установленные дополнения',
'Version'						=>	'Версия %s.',
'Hotfix'						=>	'Исправление',
'Installed hotfixes'			=>	'Установленные исправления',
'Installed extensions warn'		=>	'<strong>ВНИМАНИЕ!</strong> Если вы удалите дополнение, то данные, связанные с ним будут удалены из базы данных и не смогут быть восстановлены путем повторной установки. Если вы хотите сохранить эти данные, то просто отключите это дополнение.',
'Uninstall extension'			=>	'Удаление дополнения',
'Uninstall hotfix'				=>	'Удаление исправления',
'Uninstall'						=>	'Удалить',
'Uninstall extension confirm'	=>	'Вы уверены, что хотите удалить дополнение "%s"?',
'Enable'						=>	'Включить',
'Disable'						=>	'Отключить',
'Extension error'				=>	'Ошибка',
'Extension loading error'		=>	'Ошибка загрузки расширения "%s".',
'Illegal ID'					=>	'ID должен содержать только буквенно-цифровые символы в нижнем регистре (a-z и 0-9) и символ подчеркивания (_).',
'Maxtestedon warning'			=>	'Данное дополнение не тестировалось на вашем PunBB и поэтому может быть несовместимо с текущей версией.',
'Missing manifest'				=>	'Отсутствует manifest.xml.',
'Failed parse manifest'			=>	'Не удается прочитать manifest.xml.',
'extension root error'			=>	'Корневой элемент дополнения неправильный или отсутствует.',
'extension/engine error'		=>	'Корневой элемент скрипта неправильный или отсутствует.',
'extension/engine error2'		=>	'Версия дополнения не поддерживается.',
'extension/id error'			=>	'Элемент extension/id неправильный или отсутствует.',
'extension/id error2'			=>	'Не правильное имя папки элемента extension/id.',
'extension/title error'			=>	'Элемент extension/title неправильный или отсутствует.',
'extension/version error'		=>	'Элемент extension/version неправильный или отсутствует.',
'extension/description error'	=>	'Элемент extension/description неправильный или отсутствует.',
'extension/author error'		=>	'Элемент extension/author неправильный или отсутствует.',
'extension/minversion error'	=>	'Элемент extension/minversion неправильный или отсутствует.',
'extension/minversion error2'	=>	'Для этого дополнения требуется версия PunBB %s или более поздняя.',
'extension/maxtestedon error'	=>	'Элемент extension/maxtestedon неправильный или отсутствует.',
'extension/note error'			=>	'Неправильный элемент extension/note.',
'extension/note error2'			=>	'Элемент extension/note неверный или неправильный атрибут.',
'extension/hooks/hook error'	=>	'Элемент extension/hooks/hook неправильный или отсутствует.',
'extension/hooks/hook error2'	=>	'Элемент extension/hooks/hook отсутствует атрибут "id".',
'extension/hooks/hook error3'	=>	'Элемент extension/hooks/hook вне границ значения атрибута "приоритет".',
'extension/hooks/hook error4'	=>	'Элемент extension/hooks/hook имеет содержание, которое не заканчивается в режиме PHP.',
'No XML support'				=>	'PHP не имеет встроенной поддержки XML. Поддержка XML необходима для установки дополнений. Для получения помощи обратитесь к документации по PHP.',
'No installed extensions'		=>	'Установленных дополнений нет.',
'No installed hotfixes'			=>	'Установленных исправлений нет.',
'No available extensions'		=>	'Нет дополнений доступных для установки или обновления.',
'No available hotfixes'			=>	'Нет исправлений доступных для установки.',
'Invalid extensions'			=>	'<strong>ВАЖНО!</strong> Список дополнений был найден в папке <strong>Extensions</strong>, но не доступен для установки или обновления, поскольку были обнаружены ошибки.',
'Extension installed'			=>	'Дополнение установлено.',
'Hotfix installed'				=>	'Исправление установлено.',
'Extension installed info'		=>	'Дополнение успешно установлено, но есть следующие уведомления.',
'Extension uninstalled'			=>	'Дополнение удалено.',
'Hotfix uninstalled'			=>	'Исправление удалено.',
'Extension uninstalled info'	=>	'Дополнение удалено, но есть следующие уведомления.',
'Install note'					=>	'Пожалуйста, прочтите перед установкой',
'Uninstall note'				=>	'Пожалуйста, прочтите после установки',
'Hotfix download failed'		=>	'Ошибка загрузки и установки дополнения. Пожалуйста, подождите несколько минут и попробуйте снова.',
'Extension disabled'			=>	'Расширение отключено',
'Extension enabled'				=>	'Дополнение включено.',
'Hotfix disabled'				=>	'Исправление отключено.',
'Hotfix enabled'				=>	'Исправление включено.',
'Extension by'					=>	'Разработчик: %s.',
'Hotfix description'			=>	'Это исправление для PunBB обнаружено с помощью системы автоматического обновления.',
'Install hotfix'				=>	'Установка исправления',
'Missing dependency'			=>	'Это дополнение не может быть установлено, если "%s" установлен и включен',
'Uninstall dependency'			=>	'Это дополнение нельзя удалить пока "%s" установлено.',
'Disable dependency'			=>	'Это дополнение нельзя отключить пока "%s" включено.',
'Disabled dependency'			=>	'Это дополнение нельзя включить пока "%s" выключено.',
'Download latest version'		=>	'Загрузить последнюю версию',

);
