<?php

// Language definitions used in viewforum.php
$lang_forum = array(

'Forum subtitle'			=>	'%1$s in this forum with details of %2$s.',
'Search subtitle'			=>	'%1$s found with details of %2$s.',
'Topics'					=>	'Тем',
'topics'					=>	'тем',
'Reply'						=>	'Ответить',
'Replies'					=>	'Ответить',
'Forum'						=>	'Форум',
'reply'						=>	'reply',
'replies'					=>	'Ответов',
'View'						=>	'View',
'Views'						=>	'Просмотров',
'views'						=>	'просмотров',
'view'						=>	'просмотр',
'Last post'					=>	'Последнее сообщение',
'last post'					=>	'последнее сообщение',
'Select topic'				=>	'Select topic: %s.',
'No replies info'			=>	'No reply information',
'No views info'				=>	'No viewing information',
'No lastpost info'			=>	'No last post information',
'by poster'					=>	'от %s',
'Item status'				=>	'%s :',
'Topic starter'				=>	'от %s',
'New posts'					=>	'Новые сообщения',
'Topic navigation'			=>	'( %s )',
'Location'					=>	'Найдено в форуме : %s',
'Pages'						=>	'Страниц',
'Post topic'				=>	'Начать новую тему',
'Login to post'				=>	'Вы должны %1$s или %2$s для открытия новой темы',
'No permission'				=>	'Извините! Открытие новых тем запрещено',
'Moved'						=>	'Перемещено:',
'Sticky'					=>	'Прикреплено',
'Closed'					=>	'Закрыто',
'Empty forum'				=>	'Пустой форум',
'No topics'					=>	'Нет открытых тем.',
'First topic nag'			=>	'Станьте автором первого сообщения в этом форуме.',
'You posted indicator'		=>	'·',
'Permalink forum'			=>	'Permanent link to this forum.',
'Forum options'				=>	'Forum options',
'Moderate forum'			=>	'Модерировать форум',
'Mark forum read'			=>	'Форум прочитан',
'RSS forum feed'			=>	'RSS подписка',
'New posts info'			=>	'Перейти к первому новому сообщению с момента вашего последнего визита.'

);
