<?php

// Russian language pack [PunBB.ru community ]
// Language definitions used in viewforum.php
$lang_forum = array(

'Forum subtitle'			=>	'%1$s in this forum with details of %2$s.',
'Search subtitle'			=>	'%1$s found with details of %2$s.',
'Topics'					=>	'Темы',
'topics'					=>	'Темы',
'Reply'						=>	'Ответить',
'Replies'					=>	'Replies',
'Forum'						=>	'Форум',
'reply'						=>	'reply',
'replies'					=>	'Ответов',
'View'						=>	'View',
'Views'						=>	'Просмотров',
'views'						=>	'Просмотров',
'view'						=>	'view',
'Last post'					=>	'Последнее сообщение',
'last post'					=>	'Последнее сообщение',
'Select topic'				=>	'Выберите тему: %s.',
'No replies info'			=>	'No reply information',
'No views info'				=>	'No viewing information',
'No lastpost info'			=>	'No last post information',
'by poster'					=>	'оставил %s',
'Item status'				=>	'%s :',
'Topic starter'				=>	'оставил %s',
'New posts'					=>	'Новые сообщения',
'Topic navigation'			=>	'( %s )',
'Location'					=>	'Найдено на форуме : %s',
'Pages'						=>	'Страниц',
'Post topic'				=>	'Начать новую тему',
'Login to post'				=>	'Чтобы создавать темы Вы должны %1$s или %2$s',
'No permission'				=>	'Извините! У вас нет прав для ответов в теме',
'Moved'						=>	'Перемещено:',
'Sticky'					=>	'Важно',
'Closed'					=>	'Закрыто',
'Empty forum'				=>	'Форум пуст',
'No topics'					=>	'Ни одной темы не создано.',
'First topic nag'			=>	'Вы можете быть первым кто создаст тему.',
'You posted indicator'		=>	'·',
'Permalink forum'			=>	'Постоянная ссылка на этот форум',
'Forum options'				=>	'Настройки форума',
'Moderate forum'			=>	'Модерировать',
'Mark forum read'			=>	'Пометить форум как прочитанный',
'RSS forum feed'			=>	'RSS',
'New posts info'			=>	'Перейти к новым сообщениям с момента Вашего последнего визита'

);
